name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: linux
            arch: amd64
            ext: ""
          - os: windows-latest
            os_name: windows
            arch: amd64
            ext: ".exe"
          - os: macos-latest
            os_name: darwin
            arch: amd64
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Set asset name
      run: echo "ASSET_NAME=csv-compare_${{ github.ref_name }}_${{ matrix.os_name }}_${{ matrix.arch }}${{ matrix.ext }}" >> $GITHUB_ENV

    - name: Build executable
      run: |
        pyinstaller --onefile --name "$ASSET_NAME" --console main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET_NAME }}
        path: dist/${{ env.ASSET_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: csv-compare_*
        merge-multiple: true
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ github.ref_name }}
        name: "csv-compare ${{ github.ref_name }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}